swagger: '2.0'
info:
  version: '1.0.0'
  title: Vogo da velha

host: localhost:8080
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /jogos:
    get:
      parameters:
        - name: finalizado
          in: query
          required: false
          type: boolean
      responses:
        '200':
          description: jogos
          schema:
            type: array
            items:
              $ref: '#/definitions/jogo'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    post:
      parameters:
        - name: jogo
          in: body
          required: true
          schema:
            $ref: '#/definitions/jogo'
      responses:
        '200':
          description: jogo
          schema:
            $ref: '#/definitions/jogo'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /jogos/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: jogo
          schema:
            $ref: '#/definitions/jogo'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    delete:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: jogo deletado
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /jogos/{id}/jogadas:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: jogador
          in: query
          required: false
          type: string
      responses:
        '200':
          description: jogadas
          schema:
            type: array
            items:
              $ref: '#/definitions/jogada'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    post:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: jogada
          in: body
          required: true
          schema:
            $ref: '#/definitions/jogada'
      responses:
        '200':
          description: jogada
          schema:
            $ref: '#/definitions/jogada'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'

definitions:
  jogo:
    type: object
    required:
      - jogador1
      - jogador2
    properties:
      id:
        type: integer
        format: int64
      jogador1:
        type: string
      jogador2:
        type: string
      finalizado:
        type: boolean
      vencedor:
        type: string
      jogadas:
        type: array
        items:
          $ref: '#/definitions/jogada'
  jogada:
    type: object
    required:
      - jogador
      - quadrante
    properties:
      id:
        type: integer
        format: int64
      jogador:
        type: string
      quadrante:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
